//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Admin.NewFolder2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Role_ID { get; set; }
        public string Role_Type { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
